Jep/node label adjustment
kieler/KLighD pull request #149
Opened 2022-12-16 13:43 UTC by Drakae

Supports the merging of labels when using NETWORK_SIMPLEX and NODE_SIZE nodeFlexibility. See pull request in elk:
[https://github.com/eclipse/elk/pull/904](url)

2022-12-19 10:57 UTC, Eddykasp commented on plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/utils/KGraphMappingUtil.xtend
> +    }
remove whitespace

2023-01-06 15:30 UTC, sailingKieler requested changes

2023-01-06 15:53 UTC, sailingKieler commented
One more remark in addition to https://github.com/eclipse/elk/pull/904#issuecomment-1373816945:

Deleting diagram elements from the view model as part of the layout application is basically a no-go as they can never be restored without re-applying the diagram synthesis.
In general, special click actions mit be associated with them, (semantic) domain information attached might be attached, which is added to SVG exports for example.

Please don't take it as an offense, but wrt. the fact that KLighD is employed in some commercial projects we cannot add such functionality if implemented this way.

2023-07-21 11:42 UTC, NiklasRentzCAU commented
Not needed anymore

2023-07-21 11:42 UTC, closed without merging